const router = require('koa-router')()
const authctrl = require('../controllers/AuthController') 
const userctrl = require('../controllers/UserController') 
const captchactrl = require('../controllers/CaptchaController') 
const uploadctrl = require('../controllers/UploadController') 
const articlectrl = require('../controllers/ArticleController') 
const commentctrl = require('../controllers/CommentController') 
const friendctrl = require('../controllers/FriendController') 

router
  .get('/', authctrl.test)
  .post('/register', authctrl.register)
  .post('/login', authctrl.login)
  .get('/logout', authctrl.logout)
  .get('/user', userctrl.getSelf)
  .post('/user/update', userctrl.update)
  .get('/user/:id', userctrl.info)
  .get('/user/:id/post', userctrl.post)
  .get('/user/:id/log', userctrl.log)
  .get('/user/:id/like', userctrl.like)
  .get('/captcha', captchactrl.fetch)
  .post('/upload', uploadctrl.upload)
  .get('/article', articlectrl.list)
  .get('/article/:id', articlectrl.detail)
  .post('/article/add', articlectrl.add)
  .post('/article/update', articlectrl.update)
  .get('/article/delete/:id', articlectrl.delete)
  .put('/article/like/:id', articlectrl.like)
  .delete('/article/like/:id', articlectrl.like)
  .post('/comment', commentctrl.add)
  .get('/comment/:id', commentctrl.fetch)
  .get('/follow', friendctrl.follow)
  .get('/unfollow', friendctrl.unfollow)
  .get('/followeeList', friendctrl.followeeList)
  .get('/followerList', friendctrl.followerList)

module.exports = router
